version: '2.4'
services:
  cpu:
    build: 
      context: ./docker/cpu
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "6006:6006"
    working_dir: /workdir
    volumes:
      - ./:/workdir
    environment:
        HASHED_PASSWORD: ${HASHED_PASSWORD}
